name: Update README

on:
  schedule:
    - cron: "* */12 * * *"  # Cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: Readme-Workflows/Readme-Workflows@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
